### ISSUE TITLE
tokenize.js missing from files field in package.json

### ISSUE THREAD

**Issue by karlkristopher** [derhuerst/vbb-stations-autocomplete#22]
Hey thanks for the library. 

I believe the` lib/tokenize.js` needs to be added to the files field in the `package.json`.

**Comment by derhuerst** [comment]
True, good catch!

Do you want to submit a PR adding just `lib`?

**Comment by derhuerst** [comment]
Fix published as `vbb-stations-autocomplete@4.6.1`. 🎉
